controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login

user_controller:
    resource: ../src/User/Controller/
    type: annotation
